version: "3.9"
services:
  tensorrt_llm-dev:
    image: tensorrt_llm/devel:latest

    network_mode: host
    ipc: host

    # For GPU usage and profiling
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 8
              capabilities: [gpu]

    volumes:
      - ..:/workspaces/tensorrt_llm:cached,rw

    environment:
      - CCACHE_DIR=/workspaces/tensorrt_llm/cpp/.ccache
      - CCACHE_BASEDIR=/workspaces/tensorrt_llm

    command: /bin/sh -c "chown -R ubuntu:ubuntu /workspaces/tensorrt_llm && while sleep 1000; do :; done"
